#MySQL is manditory for this plugin
#Login information
host: localhost
port: 3306
username: root
password: password

#Database name (doesn't require adjusting)
database_publicbuilds: minecraft_publicbuilds
database_points: minecraft_points
database_uknet: minecraft_uknet

pointsData: 
messagesPerPoint: 30

messageChannel: GlobalMessages